"""Vision Intelligence data classes — roadmap Phase 14, master spec §15/§16.
Pure data contract, no I/O, no model calls — see vision_model.py for the
interface and minicpm_vlm.py for the concrete Ollama/MiniCPM-V adapter.

`VisionObservation` and `CompactCrowdMetricsSummary` are Pydantic models
(not plain dataclasses) because `VisionObservation` (via a small wrapper —
see minicpm_vlm.py's `_ObservationDraft`) becomes the literal JSON schema
constrained against Ollama's `format` parameter. `VisionInput` and
`VisionAnalysisResult` are plain dataclasses — internal request/result
wrappers, never serialized as a schema themselves.
"""

import enum
import uuid
from dataclasses import dataclass

from pydantic import BaseModel, Field

from app.pipeline.frame import Frame
from app.pipeline.risk_state import RiskState

# Reasonable bound for a scene-evidence description: enough for a few
# descriptive sentences of what's visible, not an unbounded essay — also
# keeps worst-case prompt/storage size and model rambling in check.
_DESCRIPTION_MAX_LENGTH = 500


class ObservationCategory(str, enum.Enum):
    # The six focus categories per §15 exactly — no facial emotion
    # recognition category exists here or anywhere in this project (§7's
    # explicit scope clarification, constitutional per §38).
    VISIBLE_OBSTRUCTION = "VISIBLE_OBSTRUCTION"
    BOTTLENECK = "BOTTLENECK"
    BARRIER = "BARRIER"
    UNUSUAL_MOVEMENT = "UNUSUAL_MOVEMENT"
    VISIBLE_COMPRESSION = "VISIBLE_COMPRESSION"
    VISIBLE_HAZARD = "VISIBLE_HAZARD"


class EvidenceType(str, enum.Enum):
    DIRECT = "DIRECT"
    INFERRED = "INFERRED"
    UNCERTAIN = "UNCERTAIN"


class NormalizedBoundingBox(BaseModel):
    """APPROXIMATE, VLM-supplied spatial grounding relative to whichever
    image the model was actually looking at (the full representative
    frame — see minicpm_vlm.py for exactly which image coordinates this is
    grounded against). NOT pixel-precise, NOT independently verified
    against any detector output — a rough pointer for a human reviewer,
    never fed back into quantitative Crowd Intelligence code."""

    x_min: float = Field(ge=0.0, le=1.0)
    y_min: float = Field(ge=0.0, le=1.0)
    x_max: float = Field(ge=0.0, le=1.0)
    y_max: float = Field(ge=0.0, le=1.0)


class VisionObservation(BaseModel):
    """One VLM-produced observation. `observation_id` is ALWAYS generated
    server-side (uuid4) after the model responds — NEVER requested from or
    trusted from the model's own output, same "IDs generated by us"
    discipline as every other entity in this project. See minicpm_vlm.py's
    `_ObservationDraft` for the actual schema sent to Ollama's `format`
    parameter, which omits this field entirely (the model is never asked
    to invent an ID we would just discard)."""

    observation_id: uuid.UUID
    category: ObservationCategory
    description: str = Field(max_length=_DESCRIPTION_MAX_LENGTH)
    region: NormalizedBoundingBox
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_type: EvidenceType


class CompactCrowdMetricsSummary(BaseModel):
    """Decision #3: a SMALL, structured summary — never raw per-cell grids
    — giving the VLM genuinely useful quantitative context without
    violating §15's "never raw heatmap images / bounding-box dumps" rule.
    `risk_state` reuses Phase 13's `RiskState` enum by identity (not a
    duplicated string literal set), same reuse discipline as Phase 12/13's
    own model definitions."""

    risk_score: float
    risk_state: RiskState
    max_density: float
    max_pressure: float
    # Phase 9's Critical Units Disclosure, carried through explicitly so a
    # reader of the raw prompt (or a future audit of what the VLM was told)
    # never mistakes this for a calibrated real-world value.
    pressure_units_disclaimer: str
    congested_cell_fraction: float
    reverse_flow_cell_fraction: float
    bottleneck_signal_present: bool
    density_confidence: float


@dataclass
class VisionInput:
    """Wraps ONE VLM analysis request. NOT sent to Ollama as a schema
    (VisionObservation/`_ObservationDraft` are the schema) — this is this
    project's own internal request-construction object, built by whatever
    orchestrates a trigger-driven VLM call (this phase's preview script;
    a real AnalysisOrchestrator, later)."""

    representative_frame: Frame  # the SAME frame whose CrowdMetrics fired the trigger
    roi_crop_bbox: tuple[float, float, float, float]  # (x_min, y_min, x_max, y_max), PIXEL-space, clamped to frame bounds
    compact_metrics: CompactCrowdMetricsSummary
    trigger_reason: str  # pass-through from Phase 13's TriggerDecision.reason


@dataclass
class VisionAnalysisResult:
    frame_number: int
    timestamp_seconds: float
    observations: list[VisionObservation]  # MAY be empty — valid, expected (§15), never fabricated
    model_name: str
    model_latency_seconds: float  # real measured wall-clock time (§33)
    sanitization_applied: bool  # always True this phase — traceability that the baseline mechanism ran
    trigger_reason: str
