"""add acute hazard evidence and decision columns

Revision ID: 3485d002eafd
Revises: 493a9a5a6f65
Create Date: 2026-08-19 00:48:59.096631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3485d002eafd'
down_revision: Union[str, Sequence[str], None] = '493a9a5a6f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


event_classification_enum = sa.Enum(
    'CROWD_CRUSH', 'STAMPEDE_LIKE_DISPERSAL', 'EXPLOSIVE_EVENT', 'FIRE_OR_SMOKE',
    'VEHICLE_INCIDENT', 'STRUCTURAL_HAZARD', 'OBSTRUCTION_OR_BARRIER',
    'OTHER_ACUTE_HAZARD', 'UNKNOWN',
    name='event_classification',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual fix (autogenerate emits ADD COLUMN with the enum type but does
    # NOT emit the corresponding CREATE TYPE for an add-column-to-existing-
    # table operation, unlike create_table — verified by running this
    # migration and hitting UndefinedObject: type "event_classification"
    # does not exist). Explicit .create(checkfirst=True) first, same
    # discipline as this project's other native-enum migration gotchas.
    event_classification_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('decision_results', sa.Column('event_classification', event_classification_enum, nullable=True))
    op.add_column('decision_results', sa.Column('structured_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evidence_packages', sa.Column('acute_hazard_signal_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('evidence_packages', sa.Column('event_window', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_packages', 'event_window')
    op.drop_column('evidence_packages', 'acute_hazard_signal_snapshot')
    op.drop_column('decision_results', 'structured_report')
    op.drop_column('decision_results', 'event_classification')
    # ### end Alembic commands ###
    # Manual addition (autogenerate does not emit this — same established
    # gotcha as Phase 2's user_role enum downgrade, see DECISIONS.md):
    # event_classification is a brand-new native Postgres enum TYPE created
    # by this migration's upgrade() — dropping the COLUMN above does not
    # drop the TYPE itself. Without this, re-running upgrade() after a
    # downgrade would fail with DuplicateObject.
    op.execute("DROP TYPE event_classification")
