"""create risk_events table

Revision ID: 3d8d3a4ed185
Revises: 5e688a56e091
Create Date: 2026-08-12 21:14:09.407328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8d3a4ed185'
down_revision: Union[str, Sequence[str], None] = '5e688a56e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('previous_state', sa.Enum('NORMAL', 'ELEVATED', 'CRITICAL', 'INCIDENT', name='risk_state'), nullable=False),
    sa.Column('new_state', sa.Enum('NORMAL', 'ELEVATED', 'CRITICAL', 'INCIDENT', name='risk_state'), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('risk_score_at_transition', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_events')
    # ### end Alembic commands ###
    # Native Postgres enum types are NOT removed by DROP TABLE alone — same
    # fix applied to session_status (Phase 4) and heatmap_type (Phase 12).
    sa.Enum(name='risk_state').drop(op.get_bind(), checkfirst=True)
