"""add acute_hazard to trigger_type enum

Revision ID: 493a9a5a6f65
Revises: 5d3027ef884a
Create Date: 2026-08-19 00:48:00.637309

"""
"""Acute-Hazard Trigger Phase: adds the new TriggerType.ACUTE_HAZARD value
to the ALREADY-EXISTING native Postgres `trigger_type` enum (created by
991ecbfe1789's evidence_packages table). Deliberately its OWN standalone
migration, run BEFORE anything references the new value — Postgres cannot
use a newly-added enum value inside the same transaction that adds it, and
this project's own established migration-gotcha entry (see DECISIONS.md,
the crowd_metrics_snapshots "DuplicateObject" note) already documents that
autogenerate does not detect or handle native-enum evolution correctly at
all, so this is hand-written rather than autogenerated.

Downgrade is intentionally a no-op with an honest limitation documented
below: Postgres has no `ALTER TYPE ... DROP VALUE`. A real reversal would
require rebuilding the enum type from scratch (rename, recreate without the
value, migrate the column, drop the old type) and would fail outright if
any row already used ACUTE_HAZARD — out of scope for this migration, same
"documented, not silently pretended away" honesty as this project's other
known limitations.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '493a9a5a6f65'
down_revision: Union[str, Sequence[str], None] = '5d3027ef884a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # autocommit_block(): ALTER TYPE ... ADD VALUE must not run inside the
    # same transaction as anything that might use the new value — this
    # migration only ADDS the value, but running it in its own autocommit
    # block avoids relying on a specific Postgres version's exact
    # in-transaction ADD VALUE behavior.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE trigger_type ADD VALUE IF NOT EXISTS 'ACUTE_HAZARD'")


def downgrade() -> None:
    # Postgres has no ALTER TYPE ... DROP VALUE — see module docstring for
    # why this is an honest no-op rather than a silently-incomplete attempt.
    pass
