"""create incidents, incident_evidence, and operator_actions tables

Revision ID: 566be3ce7c7b
Revises: b4f8bc1e834e
Create Date: 2026-08-15 13:31:13.254585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566be3ce7c7b'
down_revision: Union[str, Sequence[str], None] = 'b4f8bc1e834e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('DETECTED', 'ACTIVE', 'RESOLVED', 'FALSE_POSITIVE', name='incident_lifecycle_status'), nullable=False),
    sa.Column('closure_reason', sa.Enum('RESOLVED', 'DISMISSED', name='closure_reason'), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'ELEVATED', name='incident_priority'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('ACKNOWLEDGE', 'DISMISS', 'RESOLVE', 'MARK_FALSE_POSITIVE', 'ESCALATE', name='operator_action_type'), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('evidence_package_id', sa.UUID(), nullable=False),
    sa.Column('decision_result_id', sa.UUID(), nullable=False),
    sa.Column('correlated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_result_id'], ['decision_results.id'], ),
    sa.ForeignKeyConstraint(['evidence_package_id'], ['evidence_packages.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_evidence')
    op.drop_table('operator_actions')
    op.drop_table('incidents')
    # ### end Alembic commands ###
    # Native Postgres enum types are NOT removed by DROP TABLE alone — same
    # fix already applied to every prior phase's new enum types.
    sa.Enum(name='incident_lifecycle_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='closure_reason').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incident_priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='operator_action_type').drop(op.get_bind(), checkfirst=True)
