"""create crowd_metrics_snapshots table

Revision ID: 5d3027ef884a
Revises: 682ff5d0e62c
Create Date: 2026-08-16 00:30:21.420288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5d3027ef884a'
down_revision: Union[str, Sequence[str], None] = '682ff5d0e62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # risk_state is a PRE-EXISTING native enum type, created by Phase 13's
    # risk_events migration — this is the FIRST time a SECOND table reuses
    # it (autogenerate doesn't know that and emits a plain sa.Enum, which
    # would try to CREATE TYPE risk_state again and fail with
    # DuplicateObject). create_type=False here means "this type must
    # already exist," matching the incidents migration's established
    # pattern of one owning migration per native enum type.
    risk_state_enum = postgresql.ENUM(
        "NORMAL", "ELEVATED", "CRITICAL", "INCIDENT", name="risk_state", create_type=False
    )

    op.create_table('crowd_metrics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_state', risk_state_enum, nullable=False),
    sa.Column('max_density', sa.Float(), nullable=False),
    sa.Column('max_pressure', sa.Float(), nullable=False),
    sa.Column('congested_cell_fraction', sa.Float(), nullable=False),
    sa.Column('reverse_flow_cell_fraction', sa.Float(), nullable=False),
    sa.Column('bottleneck_signal_present', sa.Boolean(), nullable=False),
    sa.Column('density_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crowd_metrics_snapshots_session_timestamp', 'crowd_metrics_snapshots', ['session_id', 'timestamp_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crowd_metrics_snapshots_session_timestamp', table_name='crowd_metrics_snapshots')
    op.drop_table('crowd_metrics_snapshots')
    # risk_state itself is NOT dropped here — risk_events (Phase 13) still
    # owns/needs it; only that table's own migration's downgrade() drops
    # the type.
    # ### end Alembic commands ###
