"""create heatmap_snapshots table

Revision ID: 5e688a56e091
Revises: 79c6469e0649
Create Date: 2026-08-12 18:26:44.386402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e688a56e091'
down_revision: Union[str, Sequence[str], None] = '79c6469e0649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heatmap_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('heatmap_type', sa.Enum('DENSITY', 'PRESSURE', 'FLOW_CONGESTION', 'RISK', 'PREDICTIVE', name='heatmap_type'), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heatmap_snapshots')
    # ### end Alembic commands ###
    # Manually added: DROP TABLE does not drop the native Postgres enum type
    # the dropped column depended on, so it must be dropped explicitly or
    # re-running upgrade() after a downgrade() fails with "type already
    # exists" (same fix as the "create analysis session tables" and "create
    # users table" migrations).
    sa.Enum(name='heatmap_type').drop(op.get_bind(), checkfirst=True)
