"""add progress tracking columns to processing_runs

Revision ID: 682ff5d0e62c
Revises: 566be3ce7c7b
Create Date: 2026-08-15 19:31:58.768544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682ff5d0e62c'
down_revision: Union[str, Sequence[str], None] = '566be3ce7c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_runs', sa.Column('frames_processed', sa.Integer(), nullable=True))
    op.add_column('processing_runs', sa.Column('total_frames', sa.Integer(), nullable=True))
    op.add_column('processing_runs', sa.Column('last_progress_update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_runs', 'last_progress_update_at')
    op.drop_column('processing_runs', 'total_frames')
    op.drop_column('processing_runs', 'frames_processed')
    # ### end Alembic commands ###
