"""add video metadata columns

Revision ID: 79c6469e0649
Revises: dfd688e3d9eb
Create Date: 2026-08-10 23:47:42.409211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c6469e0649'
down_revision: Union[str, Sequence[str], None] = 'dfd688e3d9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_assets', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('video_assets', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('video_assets', sa.Column('frame_count', sa.Integer(), nullable=True))
    op.add_column('video_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('video_assets', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_assets', 'height')
    op.drop_column('video_assets', 'width')
    op.drop_column('video_assets', 'frame_count')
    op.drop_column('video_assets', 'duration_seconds')
    op.drop_column('video_assets', 'fps')
    # ### end Alembic commands ###
