"""create evidence_packages and evidence_items tables

Revision ID: 991ecbfe1789
Revises: 3d8d3a4ed185
Create Date: 2026-08-15 00:20:47.234255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '991ecbfe1789'
down_revision: Union[str, Sequence[str], None] = '3d8d3a4ed185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('trigger_type', sa.Enum('NONE', 'RISK', 'FALLBACK', 'OPERATOR', name='trigger_type'), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('model_config_id', sa.UUID(), nullable=False),
    sa.Column('crowd_metrics_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vision_observations_present', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('binding_constraint', sa.Text(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('representative_frame_path', sa.Text(), nullable=False),
    sa.Column('roi_crop_path', sa.Text(), nullable=False),
    sa.Column('roi_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_package_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('VISIBLE_OBSTRUCTION', 'BOTTLENECK', 'BARRIER', 'UNUSUAL_MOVEMENT', 'VISIBLE_COMPRESSION', 'VISIBLE_HAZARD', name='observation_category'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_type', sa.Enum('DIRECT', 'INFERRED', 'UNCERTAIN', name='evidence_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region_x_min', sa.Float(), nullable=False),
    sa.Column('region_y_min', sa.Float(), nullable=False),
    sa.Column('region_x_max', sa.Float(), nullable=False),
    sa.Column('region_y_max', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_package_id'], ['evidence_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_items')
    op.drop_table('evidence_packages')
    # ### end Alembic commands ###
    # Native Postgres enum types are NOT removed by DROP TABLE alone — same
    # fix already applied to session_status (Phase 4), heatmap_type (Phase
    # 12), and risk_state (Phase 13).
    sa.Enum(name='observation_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='evidence_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='trigger_type').drop(op.get_bind(), checkfirst=True)
