"""create analysis session tables

Revision ID: dfd688e3d9eb
Revises: f0c38b186f9e
Create Date: 2026-08-10 23:15:06.390546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd688e3d9eb'
down_revision: Union[str, Sequence[str], None] = 'f0c38b186f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detector_model', sa.String(), nullable=False),
    sa.Column('detector_runtime', sa.String(), nullable=False),
    sa.Column('vlm_model', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detector_model', 'detector_runtime', 'vlm_model', 'llm_model', name='uq_model_configs_snapshot')
    )
    op.create_table('analysis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('model_config_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='session_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='processing_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_runs')
    op.drop_table('analysis_sessions')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
    # Manually added: DROP TABLE does not drop the native Postgres enum types
    # the dropped columns depended on, so they must be dropped explicitly or
    # re-running upgrade() after a downgrade() fails with "type already
    # exists" (same fix as the earlier "create users table" migration).
    sa.Enum(name='processing_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='session_status').drop(op.get_bind(), checkfirst=True)
