"""add predictive_projection_snapshot to evidence_packages

Revision ID: f2eb5cd87669
Revises: 991ecbfe1789
Create Date: 2026-08-15 00:57:32.029413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2eb5cd87669'
down_revision: Union[str, Sequence[str], None] = '991ecbfe1789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_packages', sa.Column('predictive_projection_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_packages', 'predictive_projection_snapshot')
    # ### end Alembic commands ###
